options:
  auto-update: true
  sell-gui-rows: 3
  locked-item: STAINED_GLASS_PANE-14
  sign-prefix: '&7[&eSell&7]'
  sellall-sign-prefix: '&a&oSell All'
  pregenerate-all-item-prices: false
  enable-menu-line: false
  enable-commands: true
shop:
  enable-hierarchy: false
  enable-logging: true
boosters:
  extension-mode: false
  refresh-every: 10
commands-on-sell: []
sound:
  enabled: true
  sound: ORB_PICKUP
shops:
  A:
    name: '&9A - Shop'
    permission: QuickSell.shop.A
    itemtype: CHEST
    lore: []
list:
- A